sudo: required #is required to use docker service in travis

language: java #can be any language, just php for example

# services:
#   - docker # required, but travis uses older version of docker :(

# after_success:
#   - docker --version  # document the version travis is using
#   - docker build -t  android-jenkins .
  